// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm37oI7t0NtbyI1sI9JRaQabbqLc_3lTs',
    appId: '1:87471755892:web:ff980bf07246161161f721',
    messagingSenderId: '87471755892',
    projectId: 'tailor-app-project-58e33',
    authDomain: 'tailor-app-project-58e33.firebaseapp.com',
    storageBucket: 'tailor-app-project-58e33.appspot.com',
    measurementId: 'G-FY2KNPREF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4TcbTGahQVCu0uxKLrfMYzuh2PipRuks',
    appId: '1:87471755892:android:de5021249ae61bc461f721',
    messagingSenderId: '87471755892',
    projectId: 'tailor-app-project-58e33',
    storageBucket: 'tailor-app-project-58e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBExji5nI4te9AjFnlcLrkE6C_QfW2tFvk',
    appId: '1:87471755892:ios:b83b16741270ea7861f721',
    messagingSenderId: '87471755892',
    projectId: 'tailor-app-project-58e33',
    storageBucket: 'tailor-app-project-58e33.appspot.com',
    iosClientId: '87471755892-v2o9o7ii215tk2aas4ktssinuh7r91u3.apps.googleusercontent.com',
    iosBundleId: 'shakilawan.com.tailorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBExji5nI4te9AjFnlcLrkE6C_QfW2tFvk',
    appId: '1:87471755892:ios:b83b16741270ea7861f721',
    messagingSenderId: '87471755892',
    projectId: 'tailor-app-project-58e33',
    storageBucket: 'tailor-app-project-58e33.appspot.com',
    iosClientId: '87471755892-v2o9o7ii215tk2aas4ktssinuh7r91u3.apps.googleusercontent.com',
    iosBundleId: 'shakilawan.com.tailorApp',
  );
}
